# Generated by Django 5.1.7 on 2025-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('guests', models.IntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
            ],
        ),
    ]
