# Generated by Django 5.1.7 on 2025-04-16 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image5',
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('amazing', 'Amazing'), ('beach', 'Beach'), ('luxury', 'Luxury'), ('countryside', 'Countryside'), ('spa', 'Spa and Wellness'), ('all', 'All Inclusive'), ('amazing-views', 'Amazing Views'), ('boutique', 'Boutique'), ('lakefront', 'Lakefront'), ('beachfront', 'Beachfront'), ('design', 'Design'), ('golf', 'Golf')], default='amazing', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image4_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image5_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.IntegerField()),
                ('total_price', models.FloatField(default=0.0)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
