# Generated by Django 5.1.7 on 2025-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image5',
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('amazing', 'Amazing'), ('beach', 'Beach'), ('luxury', 'Luxury'), ('countryside', 'Countryside'), ('spa', 'Spa and Wellness'), ('all', 'All Inclusive'), ('amazing-views', 'Amazing Views'), ('boutique', 'Boutique'), ('lakefront', 'Lakefront'), ('beachfront', 'Beachfront'), ('design', 'Design'), ('golf', 'Golf')], default='amazing', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image4_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image5_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
