# Generated by Django 5.1.7 on 2025-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='suggestion',
            field=models.TextField(default=''),
        ),
    ]
