# Generated by Django 5.1.7 on 2025-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_feedback_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('reservation', 'Reservation Inquiry'), ('feedback', 'Feedback'), ('support', 'General Support'), ('partnership', 'Business Partnership'), ('other', 'Other')], default='support', max_length=50),
        ),
    ]
