# Generated by Django 5.1.7 on 2025-04-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('reserve', 'Reserve Inquiry'), ('general', 'GeneralSupport'), ('bussiness', 'Bussiness Partnership'), ('other', 'Other')], default='support', max_length=50),
        ),
    ]
