# Generated by Django 5.2 on 2025-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
