# Generated by Django 5.2 on 2025-05-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_delete_contactmessage_feedback_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
