# Generated by Django 5.2 on 2025-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_alter_appuser_is_active_alter_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
